import "./globals.css";
import { AuthProvider } from "@/app/_contexts/AuthContext";
import { Header } from "@/app/_components/Header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Secure Auth App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <AuthProvider>
          <Toaster position="top-right" />
          <Header />
          <div className="py-8">
            <main className="mx-auto max-w-3xl px-4">{props.children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}